### PR TITLE
Add option for checking class constructor docstrings in `__init__`

### LINKED ISSUE #195: Enhancement suggestion: Add capability to check __init__ document in its own docstring
Firstly, thanks for docsig, it's great!

One area where I still am finding 'mistakes' in my docstring signatures though is where I've added the description of an `__init__` signature in the `__init__` docstring itself, rather than the class docstring. If I miss a parameter, or document a parameter that doesn't exist there, there's no way to configure docsig to raise an error, without it also being unhappy about the signature being documented in the `__init__` docstring rather than the class docstring.

<details><summary>Minimal example</summary>
<p>

I think this is understood that this isn't covered (it's on the README page), so putting this inside a 'details' as I think my job here is more persuading that it's worth docsig supporting this, rather than describing what it currently does - but I want to have that too of course.

For a minimal example, consider this code:

```python
class SomeClass:
    \"\"\"This class does something useful.\"\"\"

    def __init__(self, first_arg: bool, second_arg: str):
        \"\"\"Create a new instance of SomeClass
        
        :param first_arg: this does exist
        :param non_existent_arg: this arg doesn't actually exist!
        \"\"\"
        pass
```

This has incorrect documentation (so rendered docs will show incorrectly), but will pass a `docsig` check with default configuration):

```python
from docsig import docsig
    
string_to_check = """
class SomeClass:
    \"\"\"This class does something useful.\"\"\"

    def __init__(self, first_arg: bool, second_arg: str):
        \"\"\"Create a new instance of SomeClass
        
        :param first_arg: this does exist
        :param non_existent_arg: this arg doesn't actually exist!
        \"\"\"
        pass
"""

docsig(string=string_to_check, check_class=True)
```

Note though that if I turn on `check_class`, even a correctly documented `__init__` will cause an error `E103: parameters missing`:

```python
from docsig import docsig
    
string_to_check = """
class SomeClass:
    \"\"\"This class does something useful.\"\"\"

    def __init__(self, first_arg: bool, second_arg: str):
        \"\"\"Create a new instance of SomeClass
        
        :param first_arg: this does exist
        :param second_arg: this exists too and completes coverage
        \"\"\"
        pass
"""

docsig(string=string_to_check, check_class=True)
```

this gives:

```
5 in SomeClass
--------------
class SomeClass:
    """
    :param None: ✖
    :param None: ✖
    """

    def __init__(✖first_arg, ✖second_arg)?:

E103: parameters missing
```

</p>
</details> 

However, I think this is a valid way of writing docstrings, and one where docsig would add value if it checked this style of writing them (I found this by realising I had made a mistake of this kind in my project).

In fact, my reading of [PEP257's multi-line docstring section](https://peps.python.org/pep-0257/#multi-line-docstrings) is that this is the recommended way of writing `__init__` signatures:

> The class constructor should be documented in the docstring for its \_\_init\_\_ method

From this paragraph on docstrings for classes:

> The docstring for a class should summarize its behavior and list the public methods and instance variables. If the class is intended to be subclassed, and has an additional interface for subclasses, this interface should be listed separately (in the docstring). The class constructor should be documented in the docstring for its \_\_init\_\_ method. Individual methods should be documented by their own docstring.

I think probably for backwards-compatibility, we would probably want to leave the check of an `__init__` docstring only running when `check_class` is `True`.

Would you be interested in docsig supporting this?

If so, I may be able to work on a PR myself, if we can agree on an approach.

<details><summary>Some initial thoughts on supporting this</summary>
<p>
My impression is that it's [these lines](https://github.com/jshwi/docsig/blob/7fc0f02c71f8cb469c41763dee2ccf0bba2f6e38/docsig/_function.py#L292-L295) (copied below for inline clarity that set the docstring of `__init__` method's to the parent class's docstring, which prevents this being possible:

```python
        self._docstring = _Docstring(
            node.doc_node if not self.isinit else self._parent.doc_node,
            ignore_kwargs,
        )
```

There's a couple of approaches that I wonder if they're worth considering:

1. allow the constructor(/`__init__`) of `_function._Docstring` to take a `str` for `node`, as well as `_ast.Const` or `None`, and then replace:
   `node.doc_node if not self.isinit else self._parent.doc_node,`
   with:
   `node.doc_node if not self.isinit else self._parent.doc_node.value + "\n" + node.doc_node.value,`
   This will fix the problems I currently have, but does allow weird things where some params are documented in the class docstring, and others in the `__init__` docstring, which is undesirable, but seems unlikely to happen.
2. Add a class method on `_function._Docstring` to create a `_Docstring` from a string, which the above code will call in the `self.isinit` case (this preserves the constructor signature of `_Docstring` but is otherwise similar to the above
3. Move the `if not self.isinit` logic inside `_Docstring.__init__`, create `_Matches(...)` for both the `__init__` docstring and the parent class docstring, and use whichever one gets matches for the `_Docstring._string`, `_Docstring._args` and `_Docstring._returns`. If neither, choose the class docstring, if both match maybe raise an error? Might have to be a new one. The downside of this is that it's a bigger change, and there's more compute involved in deciding which docstring to use for `__init__` methods, which is then 'throwaway work' if `check_class` isn't even true.

</p>
</details>

### PR DESCRIPTION
**Pull request by EFord36**
Closes #195

Not sure if the test setup will be exactly as you want - let me know what you think, I'm happy to change. In particular, while it does check that things fail and succeed as expected, it's not currently checking the exact error/output, which is a shame, but I couldn't think of a good way of doing it. Equally the actual code change is probably small enough that the tests don't have to be super exhaustive - really 6 lines of changes 'logic', which is really one `if/else`.

I made `--check-class` and `--check-class-constructor` mutually incompatible, as it wasn't obvious how you could made it work if both were specified without ending up with ugly code (and even what the behaviour 'should' be if a user passes maybe isn't obvious).

### CODE REVIEW

**Comment by EFord36** [comment]
gah, I messed up checking for merge conflicts - forgot to sync my fork with the upstream.

It's getting late my time, so I'll look at this tomorrow. Feel free to look at the code if you want, I wouldn't think the merge conflicts will be catastrophic to the whole approach.

**Comment by jshwi** [comment]
This looks great

I really like this, I wouldn't have through to do it
```
➜ docsig -cC
usage: docsig [-h] [-v] [-c | -C] [-D] [-o] [-p] [-P] [-i] [-a] [-k] [-n] [-S] [-s STR] [-d LIST] [-t LIST] path [path ...]
docsig: error: argument -C/--check-class-constructor: not allowed with argument -c/--check-class
```
I resolved the conflicts locally and ran everything and this is all holding up, everything passed, and I ran the cli and it looks good

So we can let the pipeline pass before I merge this to master you can either
`git rebase master`, resolve the conflicts and then `git push --force`, that would probably be cleanest?
Or if you don't like rebase you can merge master into this branch, resolve the conflicts and push the updated commit to this PR

With the package's conflicts there only seem to be a few changed args and maybe one inheritance change

The tests were a little messier, I'd probably just checkout the tests to HEAD and then add your new tests to the bottom of the files. Look forward to seeing your update

Cheers mate!
Stephen

**Comment by EFord36** [comment]
Rebase done!

One change I made in addition to the rebase - I noticed in the docstring of `test_check_class_constructor` I had accidentally left in two lines that didn't relate to this test (I wrote the test by copy-pasting another one and modifying):

```text
    All tests that fail such as with ``--check-class`` should be prefixed
    with ``FClass``, and these particular tests should all fail.
```

So I've deleted these now.

**Comment by jshwi** [comment]
Awesome, I'm ready to merge

The CI will pass if you just run `pyaud whitelist -f`
It's a bit redundant, as only the line numbers have changed on it, I originally wrote it to exclude the full path and only from the repository root as the diff would be huge from machine to machine, dir to dir. Really it should just be there to update new funcs/classes, I'll look at that some time

but yeah, in the meantime just run that and amend the commit and it should be good to go

Thanks!
Stephen

**Comment by EFord36** [comment]
I hadn't thought too much about the rendering of the errors - it looks the same as for with `--check-class`, so with a separate 'class' for the description, and the `__init__` for the actual signature. I think that's fine, but let me know if you think it needs changing (random example from my project):

```text
class OntologyMatcher:
    """
    :param span_key: ✖
    :param None: ✖
    :param None: ✖
    :param None: ✖
    :param None: ✖
    """

    def __init__(✖nlp, ✖name, ✖span_key, ✖match_id_sep, ✖parser_name_to_entity_type)?:

E101: parameters out of order
E103: parameters missing
```

**Comment by jshwi** [comment]
imo that's fine
I don't really want to support the rendering of errors anymore, I use the summary option
It seemed to make sense when I first started this, but it doesn't overall make that much of a difference, imo

**Comment by EFord36** [comment]
just fixed the whitelist - sorry about that - didn't deal with it properly in the rebase, but thought I was in the clear with the pre-commit hooks all passing. Oops!

**Pull request merged**
