### PR TITLE
fix: recognize postional-only arguments

### PR DESCRIPTION
**Pull request by fresh2dev**
Issue: https://github.com/jshwi/docsig/issues/144

Not thoroughly tested, but it resolves the issue for me.

### CODE REVIEW

**Comment by jshwi** [comment]
Thanks for spotting this one, looks good so far! 
```bash
$ read -r -d '' string <<'EOF'
def starmap(
    # self, docsig cannot confirm this is a method
    fun: Callable[..., Any],
    iterable: Sequence[Sequence[Any]],
    /,
    *args: Any,
    timeout: float = 0,
    show_progress: bool | None = None,
    **kwargs: Any,
) -> list[Job]:
    """Submits many jobs to the queue.

    One for each sequence in the iterable.
    Waits for all to finish, then returns the results.

    Args:
        fun: ...
        iterable: ...
        *args: static arguments passed to the function.
        timeout: ...
        show_progress: ...
        **kwargs: static keyword-arguments passed to the function.

    Returns:
        ...
    """
    pass
EOF

$ docsig -s "$string"
# 1
# 	E102: includes parameters that do not exist
# 	E101: parameters out of order

$ echo $?
# 1

$ git checkout support-pos-only-args
# Switched to branch 'support-pos-only-args'

$ docsig -s "$string"
# 
$ echo $?
# 0
```
I'll kick off the CI

**Comment by jshwi** [comment]
Ok, I know how to make this pass, can you add this test to tests/__init__.py (bottom of the file is fine)
The setup is a little unconventional, but with it we can put together a lot of tests with a single addition (6 in this instance)
```bash
$ poetry run pytest | grep issue-1-1-4 | cat -n
     1	tests/_test.py::test_ignore_kwargs[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 11%]
     2	tests/_test.py::test_exit_status[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 51%]
     3	tests/_test.py::test_string_argument[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 62%]
     4	tests/_test.py::test_ignore_no_params[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 77%]
     5	tests/_test.py::test_ignore_args[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 90%]
     6	tests/_test.py::test_no_stdout[p-issue-1-1-4-pos-only-args-w-args-w-kwargs-n] PASSED [ 91%]
```
The name of the test effects how it will be processed (though it's not especially important if you copy and paste it to the end of the file, just that the name needs to remain the same)
* `P`: We expect it to pass without extra conditions
* `WArgs`: This includes *args, so we expect it to fail with `-a/--ignore-args`
* `WKwargs`: This includes *kwargs, so we expect it to fail with `-k/--ignore-kwargs`
```
@_templates.register
class _PIssue114PosOnlyArgsWArgsWKwargsN(_BaseTemplate):
    @property
    def template(self) -> str:
        return """
def starmap(
    fun: Callable[..., Any],
    iterable: Sequence[Sequence[Any]],
    /,
    *args: Any,
    timeout: float = 0,
    show_progress: bool | None = None,
    **kwargs: Any,
) -> list[Job]:
    \"\"\"Submits many jobs to the queue.

    One for each sequence in the iterable.
    Waits for all to finish, then returns the results.

    Args:
        fun: ...
        iterable: ...
        *args: static arguments passed to the function.
        timeout: ...
        show_progress: ...
        **kwargs: static keyword-arguments passed to the function.

    Returns:
        ...
    \"\"\"
"""

    @property
    def expected(self) -> str:
        return ""
```
More on how the tests are processed here https://github.com/jshwi/docsig/blob/master/CONTRIBUTING.md#testing
With this we're still not hitting line 184 in `docsig._function`
```
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
docsig/__init__.py        5      0   100%
docsig/_config.py        26      0   100%
docsig/_core.py          30      0   100%
docsig/_display.py      120      0   100%
docsig/_function.py     180      1    99%   184
docsig/_main.py           5      0   100%
docsig/_module.py        42      0   100%
docsig/_objects.py       17      0   100%
docsig/_report.py       119      0   100%
docsig/_utils.py          6      0   100%
docsig/_version.py        1      0   100%
docsig/messages.py       19      0   100%
tests/__init__.py      2142      0   100%
tests/_test.py           85      0   100%
tests/_utils.py           7      0   100%
tests/conftest.py        21      0   100%
tests/misc_test.py       49      0   100%
---------------------------------------------------
TOTAL                  2874      1    99%
```
The reason for this is that this is not actually doing anything
```
-        if ismethod and not isstaticmethod and arguments.args:
-            arguments.args.pop(0)
+        if ismethod and not isstaticmethod:
+            if arguments.posonlyargs:
+                arguments.posonlyargs.pop(0)
+            elif arguments.args:
+                arguments.args.pop(0)
```
The arg being popped is only relevant for `self`, as (at least for now) the tool completely ignores `self` when handling a method. All it does is remove `self` when it confirms this is in fact a method, and this is also not a static method (in which case it must include `self`)

Please add the test, and undo that change, and the CI should pass 😄, then I'll merge this and publish the updated release to PyPI so it's ready to use

Again thank you! I'm happy you spotted this one, and really appreciate you submitting the PR and actively resolving the issue

Cheers!
Stephen

**Comment by jshwi** [comment]
Hi @fresh2dev,
Just added a test, all looks good
I'll revert this
```bash
diff --git a/docsig/_function.py b/docsig/_function.py
index 21e9f7f..ff8c133 100644
--- a/docsig/_function.py
+++ b/docsig/_function.py
@@ -178,12 +178,8 @@ class _Signature(_DocSig):
         ignore_kwargs: bool = False,
     ) -> None:
         super().__init__(ignore_args, ignore_kwargs)
-
-        if ismethod and not isstaticmethod:
-            if arguments.posonlyargs:
-                arguments.posonlyargs.pop(0)
-            elif arguments.args:
-                arguments.args.pop(0)
+        if ismethod and not isstaticmethod and arguments.args:
+            arguments.args.pop(0)

         self._args.extend(
             a if isinstance(a, Param) else Param(name=a.name)
```
As all it is doing is removing the first arg (`self`) in a non-static method
And as such the condition is never met and is not being covered
```
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
docsig/__init__.py        5      0   100%
docsig/_config.py        26      0   100%
docsig/_core.py          30      0   100%
docsig/_display.py      120      0   100%
docsig/_function.py     180      1    99%   184
docsig/_main.py           5      0   100%
docsig/_module.py        42      0   100%
docsig/_objects.py       17      0   100%
docsig/_report.py       119      0   100%
docsig/_utils.py          6      0   100%
docsig/_version.py        1      0   100%
docsig/messages.py       19      0   100%
tests/__init__.py      2142      0   100%
tests/_test.py           85      0   100%
tests/_utils.py           7      0   100%
tests/conftest.py        21      0   100%
tests/misc_test.py       49      0   100%
---------------------------------------------------
TOTAL                  2874      1    99%
```
Thanks again for spotting this and taking the time out to fix it, really appreciate it! I'll get this to pypi so it can be used.

**Comment by fresh2dev** [comment]
Hey, thanks for the prompt attention on this! Regarding this revert...

```diff
diff --git a/docsig/_function.py b/docsig/_function.py
index 21e9f7f..ff8c133 100644
--- a/docsig/_function.py
+++ b/docsig/_function.py
@@ -178,12 +178,8 @@ class _Signature(_DocSig):
         ignore_kwargs: bool = False,
     ) -> None:
         super().__init__(ignore_args, ignore_kwargs)
-
-        if ismethod and not isstaticmethod:
-            if arguments.posonlyargs:
-                arguments.posonlyargs.pop(0)
-            elif arguments.args:
-                arguments.args.pop(0)
+        if ismethod and not isstaticmethod and arguments.args:
+            arguments.args.pop(0)

         self._args.extend(
             a if isinstance(a, Param) else Param(name=a.name)
```

...while I don't understand the total implications, I do understood the intent. What I observed is that, when *any* arg is positional-only, `self` is *inherently* a positional-only arg as well, and it exists as the first item in `arguments.posonlyargs`. i.e., `self` (or `cls`) exists in one or the other (`args` or `posonlyargs`), depending on whether `/` is provided in the function signature.

```
 'args': [],
 'posonlyargs': [<AssignName.self l.819 at 0x7f53bc2d8b20>,
                 <AssignName.fun l.820 at 0x7f53bc2d8b50>,
                 <AssignName.iterable l.821 at 0x7f53bc2d8b80>],
```

That's why I made the change that I did. While the original logic I wrote seems appropriate, I of course trust your judgement (and your tests!) more than my limited understanding. :clinking_glasses:

**Comment by jshwi** [comment]
hey @fresh2dev,
i might have jumped the gun with this one, could you please submit that change with a PR again? I'll add a new test

**Comment by jshwi** [comment]
All good I was able to cherry pick the commit, so you're changes still apply, sorry about that, I should have enquired further as to the purpose of the change. You're right, the results are different with a class, I'll push this change to pypi now

**Comment by jshwi** [comment]
ok that should be implemented now 😄 pushing to pypi

**Comment by fresh2dev** [comment]
Godspeed sir :rocket: Thanks again :fist_right: :fist_left:

**Comment by jshwi** [comment]
And thank you for your work in improving this package! 😄

**Pull request merged**
